version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - $ext_port:$ext_port/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      lb: 'true'
  httpd:
    image: httpd
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
